export { default as createWorker } from './createWorker.js'
export { default as escolherCarteira } from './escolherCarteira.js'
export { default as escolherMinimo } from './escolherMinimo.js'
export { default as escolherPorcentagem } from './escolherPorcentagem.js'
export { default as escolherNumWorkers } from './escolherWorkers.js'
export { default as fazerPergunta } from './fazerPergunta.js'
export { default as rl } from './readInterface.js'